### ISSUE TITLE
Missing Project Reference DLL "Landis.Library.BiomassCohorts-vBrowse"

### ISSUE THREAD

**Issue by aruzicka555** [LANDIS-II-Foundation/Extension-Biomass-Browse#2]
Project references this DLL but it is not included in the Support-DLL repository. DLL needs to be found in order for the project to build. @rmscheller @brmiranda

**Comment by rmscheller** [comment]
Brian Miranda wrote:
"The Biomass Browse extension uses a customized version of the biomass cohort library because we need to track additional cohort attributes.  In the end, this means we will need to release a version of Biomass Succession that uses this cohort library and is compatible with this extension.  There is still some work to be done on that front.  For the time being we have ‘vBrowse’ branches for Biomass Succession and Biomass Cohort Library that work with the extension.  I don’t know when I will get around to completing this, as I have way too much on my plate.  The browse papers are out, but there hasn’t been a demand for the extension yet."
