### ISSUE TITLE
Incorrect Code Prevents Build

### ISSUE THREAD

**Issue by aruzicka555** [LANDIS-II-Foundation/Extension-Biomass-Browse#3]
Incorrect code in the project prevents it from being built. This code is in PartialDisturbance.cs Lines 145, 167, and 190 (they all appear to be incorrect function declarations). Also errors on lines 163, 186, and 208 in PartialDisturbance.cs. These errors pertain to methods within ISiteCohorts the code attempts to call which Visual Studio says do not exist. There are also errors in Event.cs lines 282, 330, 357, 383, 384, 482, 491, and 518. These errors are due to the code again referencing methods which Visual Studio says do not exist for the ICohort class. @rmscheller @brmiranda

**Comment by rmscheller** [comment]
Brian Miranda says:
"The Biomass Browse extension uses a customized version of the biomass cohort library because we need to track additional cohort attributes.  In the end, this means we will need to release a version of Biomass Succession that uses this cohort library and is compatible with this extension.  There is still some work to be done on that front.  For the time being we have ‘vBrowse’ branches for Biomass Succession and Biomass Cohort Library that work with the extension.  I don’t know when I will get around to completing this, as I have way too much on my plate.  The browse papers are out, but there hasn’t been a demand for the extension yet."
